<a href="https://colab.research.google.com/github/SakshiGehani/J015_NLPassignments/blob/ClassWork/CW7_TF_IDF_spamDetection_J015_14_01_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from google.colab import files

In [3]:
upload = files.upload()

Saving SMSSpamCollection to SMSSpamCollection


In [0]:
df = pd.read_csv("SMSSpamCollection", sep="\t", names=["label", "text"])      ## reading tab separated file

In [5]:
df.head()

label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
# importing required modules
import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re
import nltk
nltk.download('words')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Unzipping corpora/words.zip.


True

In [0]:
## Preprocessing data

stop_words = set(stopwords.words('english'))      # for unique entries -> set()
words = set(nltk.corpus.words.words())
def preprocess(sen):
  sen = sen.lower()
  no_punc = sen.translate(sen.maketrans('', '', '!"$%&\'()#@*+,-./:;<=>?[\\]^_`{|}~'))      ## removing all punctuation marks
  filtered = no_punc.translate(no_punc.maketrans('', '', '#@0123456789'))           ## removing digits
  tokens = word_tokenize(filtered)                        ## creating a list of tokens
  no_stop_words = [w for w in tokens if not w in stop_words]     # eliminate stop words;  returns list of lists
  sent = " ".join(w for w in no_stop_words)
  sent = " ".join(w for w in nltk.wordpunct_tokenize(sent) \
            if w.lower() in words or not w.isalpha())                ## eliminating all non-english words
  
  return sent

In [8]:
corpus=df.text.apply(preprocess)
print(corpus)

0       go point crazy available n great world la e bu...
1                                                   lar u
2       free entry win fa cup final st may text fa rec...
3                         u dun say early u c already say
4                           dont think goes around though
                              ...                        
5567    time tried contact u u £ pound prize claim eas...
5568                               b going esplanade home
5569                                            pity mood
5570    guy like id interested something else next wee...
5571                                            true name
Name: text, Length: 5572, dtype: object


In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [0]:
X = vectorizer.fit_transform(corpus)

In [11]:
print(vectorizer.get_feature_names())

['aa', 'abbey', 'abdomen', 'ability', 'able', 'abnormally', 'abroad', 'absence', 'absolutely', 'abstract', 'abuse', 'academic', 'accent', 'accept', 'access', 'accessible', 'accident', 'accidentally', 'accommodation', 'accordingly', 'account', 'accounting', 'accumulation', 'ache', 'achieve', 'acid', 'across', 'act', 'actin', 'acting', 'action', 'activate', 'active', 'actor', 'actual', 'actually', 'ad', 'add', 'added', 'addicted', 'address', 'adjustable', 'administrator', 'admirer', 'admission', 'admit', 'adore', 'adult', 'advance', 'adventure', 'advice', 'advise', 'ae', 'aeronautics', 'aeroplane', 'affair', 'affection', 'affectionate', 'affidavit', 'afford', 'afraid', 'aft', 'afternoon', 'afternoons', 'afterwards', 'age', 'agency', 'agent', 'aging', 'ago', 'agree', 'ah', 'aha', 'ahead', 'aid', 'aint', 'air', 'airport', 'ak', 'aka', 'al', 'album', 'alcohol', 'alert', 'algebra', 'alibi', 'alive', 'allow', 'almost', 'alone', 'along', 'already', 'alright', 'also', 'alter', 'although', 'alwa

In [12]:
print(X.shape)

(5572, 3633)


In [13]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
#converting the count vectorizer array into input dataframe

X = pd.DataFrame(X.toarray(), columns=(vectorizer.get_feature_names()))

In [15]:
X.head()

aa  abbey  abdomen  ability  able  ...  zac  zebra  zed  zoom  〨ud
0  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0
1  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0
2  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0
3  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0
4  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0

[5 rows x 3633 columns]

In [16]:
X.columns

Index(['aa', 'abbey', 'abdomen', 'ability', 'able', 'abnormally', 'abroad',
       'absence', 'absolutely', 'abstract',
       ...
       'young', 'younger', 'youve', 'yr', 'yummy', 'zac', 'zebra', 'zed',
       'zoom', '〨ud'],
      dtype='object', length=3633)

In [17]:
df_new = X.copy()
df_new.head()

aa  abbey  abdomen  ability  able  ...  zac  zebra  zed  zoom  〨ud
0  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0
1  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0
2  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0
3  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0
4  0.0    0.0      0.0      0.0   0.0  ...  0.0    0.0  0.0   0.0  0.0

[5 rows x 3633 columns]

In [0]:
df_new["label"] = df.label

In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_new['label'] = le.fit_transform(df_new['label'])       ## label encoding the spam label column

In [20]:
df_new.head()

aa  abbey  abdomen  ability  able  ...  zebra  zed  zoom  〨ud  label
0  0.0    0.0      0.0      0.0   0.0  ...    0.0  0.0   0.0  0.0      0
1  0.0    0.0      0.0      0.0   0.0  ...    0.0  0.0   0.0  0.0      0
2  0.0    0.0      0.0      0.0   0.0  ...    0.0  0.0   0.0  0.0      1
3  0.0    0.0      0.0      0.0   0.0  ...    0.0  0.0   0.0  0.0      0
4  0.0    0.0      0.0      0.0   0.0  ...    0.0  0.0   0.0  0.0      0

[5 rows x 3634 columns]

In [0]:
from sklearn.model_selection import train_test_split as tts
# splitting into train-test
X_train, X_test, y_train, y_test = tts(X, df['label'], test_size=0.3, random_state=42)

In [22]:
!pip install xgboost

In [0]:
# applying base model XGBoost on the data returned by the tf/idf vectorizer

from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

# fit model on training data
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
# make predictions for test data
xg_pred = xgb.predict(X_test)

In [26]:
xg_probs = xgb.predict_proba(X_test)
print("\n Classification Report for test data : \n", classification_report(xg_pred, y_test))



 Classification Report for test data : 
               precision    recall  f1-score   support

         ham       1.00      0.96      0.98      1510
        spam       0.70      0.97      0.81       162

    accuracy                           0.96      1672
   macro avg       0.85      0.96      0.89      1672
weighted avg       0.97      0.96      0.96      1672



In [25]:
xg_probs1 = xgb.predict_proba(X_train)
print("\n Classification Report for train data : \n", classification_report(xgb.predict(X_train), y_train))



 Classification Report for train data : 
               precision    recall  f1-score   support

         ham       1.00      0.96      0.98      3505
        spam       0.74      0.98      0.84       395

    accuracy                           0.96      3900
   macro avg       0.87      0.97      0.91      3900
weighted avg       0.97      0.96      0.96      3900

